project_name: tau-cli
release:
  github:
    owner: taubyte
    name: tau-cli

  draft: false
  replace_existing_draft: false
  prerelease: auto

  name_template: ""
  disable: false
  skip_upload: false

builds:
  - id: "linux"
    main: "./tools/tau/main.go"
    binary: "tau"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
      - GOAMD64=v2

changelog:
  disable: true

checksum:
  disable: true

archives:
  - files:
      - none*
